# Importando as libs

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
df_train = pd.read_csv('../data/train.csv' ).drop(axis = 1, labels = 'PassengerId')
df_train = df_train.convert_dtypes()
df_train

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,<NA>,S
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925,<NA>,S
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1,C123,S
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.05,<NA>,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0,<NA>,S
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0,B42,S
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,<NA>,1,2,W./C. 6607,23.45,<NA>,S
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0,C148,C
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,<NA>,Q

# Entendendo os dados

In [7]:
df_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    Int64
 1   Pclass    891 non-null    Int64
 2   Name      891 non-null    string
 3   Sex       891 non-null    string
 4   Age       714 non-null    Float64
 5   SibSp     891 non-null    Int64
 6   Parch     891 non-null    Int64
 7   Ticket    891 non-null    string
 8   Fare      891 non-null    Float64
 9   Cabin     204 non-null    string
 10  Embarked  889 non-null    string
dtypes: Float64(2), Int64(4), string(5)
memory usage: 81.9 KB

In [8]:
df_train.columns = ['survived', 'class', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare', 'cabin', 'embarked']

# Limpando os dados

## Pclass

Essa coluna não precisa ser tratada.

In [9]:
df_train['class'].value_counts()

3    491
1    216
2    184
Name: class, dtype: Int64

## Name

Resolvemos adicionar uma coluna nova com o titulo de cada passageiro, isto é, senhor senhora...

In [12]:
title = df_train.name.apply(func = lambda i: i.split(',')[1].split('.')[0].strip())

In [13]:
df_train.loc[:,'title'] = title

In [14]:
df_train

,survived,class,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,title
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,<NA>,S,Mr
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925,<NA>,S,Miss
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1,C123,S,Mrs
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.05,<NA>,S,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0,<NA>,S,Rev
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0,B42,S,Miss
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,<NA>,1,2,W./C. 6607,23.45,<NA>,S,Miss
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0,C148,C,Mr
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,<NA>,Q,Mr

## sex

Trocamos 'male' e 'female' para 0 e 1 respectivamente.

In [15]:
df_train.sex.apply(func = lambda x: 1 if x == 'male' else 0 )

0      1
1      0
2      0
3      0
4      1
      ..
886    1
887    0
888    0
889    1
890    1
Name: sex, Length: 891, dtype: int64

## age

Resolvemos preencher os valores vazios com base na média de idade do grupo no qual a pessoa se encaixa, grupo esse formado com base na coluna title. Ou seja, se uma pessoa possui um valor vazio na coluna idade e na coluna title essa pessoa possui o title igual a Mr, logo a idade dessa pessoa será preenchida com base na média de todas as pessoas que possuem o title igual a Mr.

In [106]:
idade_na_index = df_train.age[df_train.age.isna()].index

titulo_na = df_train.title[idade_na]

titulo_na.apply(func = lambda x: media_age_title[x])


for i in titulo_na.apply(func = lambda x: media_age_title[x]).index:
    df_train.loc[ i ,'age'] = titulo_na.apply(func = lambda x: media_age_title[x])[i]
    
df_train

,survived,class,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,title
0,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,<NA>,S,Mr
1,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Mrs
2,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.925,<NA>,S,Miss
3,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1,C123,S,Mrs
4,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.05,<NA>,S,Mr
...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0,<NA>,S,Rev
887,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0,B42,S,Miss
888,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,22.0,1,2,W./C. 6607,23.45,<NA>,S,Miss
889,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0,C148,C,Mr
890,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,<NA>,Q,Mr

In [25]:
df_new = df_train.copy()

for pos in df_new[df_new['age'].isna()].index:
    df_new.loc[pos, 'age'] = df_new[df_new.title == df_new.title[pos]]['age'].mean().round(0)